export const FETCH_NOTES_REQUEST = 'FETCH_NOTES_REQUEST'
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS'
export const FETCH_NOTES_FAILURE = 'FETCH_NOTES_FAILURE'

export const ADD_NOTE_REQUEST = 'ADD_NOTE_REQUEST'
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS'
export const ADD_NOTE_FAILURE = 'ADD_NOTE_FAILURE'

export const EDIT_NOTE_REQUEST = 'EDIT_NOTE_REQUEST'
export const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS'
export const EDIT_NOTE_FAILURE = 'EDIT_NOTE_FAILURE'

export const DELETE_NOTE_OPTIMISTIC = 'DELETE_NOTE_OPTIMISTIC'
